name: Server-Ultimate-Protection
on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Force Wake Up and Renew
        run: |
          curl -s -L --max-time 30 --retry 3 "https://gold.magmanode.com/server?id=985993" \
          -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0"
