name: Server-Ultimate-Protection
on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Force Wake Up
        run: |
          curl -I "https://gold.magmanode.com/server?id=985993"
